### ISSUE TITLE
TypeError: switch_value is not a constructor

### ISSUE THREAD

**Issue by frederikhors** [rixo/rollup-plugin-svelte-hot#10]
I'm having this error with `npm run dev` (nollup)

`Uncaught (in promise) TypeError: switch_value is not a constructor`

using this component:

```
<script>
  export let component
</script>

{#await component}
  Loading...
{:then cmp}
  <svelte:component this={cmp.default} />
{/await}
```

Using `npm run dev:rollup` works.

**Comment by rixo** [comment]
Thanks for reporting. Would you be so kind as to provide a minimal repro? A fork of the hot template with just this component added in context would do here ;-) and it would help a lot because it's not obvious to me how you're using this component.

This is probably a problem in Nollup, if HMR works normally with the Rollup plugin, but I might be able to track or narrow down the problem.

**Comment by frederikhors** [comment]
Fixed in my code.

I was using a wrong `chunkFileNames` in `rollup.config.js`.

Thanks, you're very kind!
