### ISSUE TITLE
Error with Nollup, not with Rollup

### ISSUE THREAD

**Issue by frederikhors** [rixo/rollup-plugin-svelte-hot#11]
I'm using https://github.com/pearofducks/svelte-match-media.

My setup works with `npm run dev:rollup`, NOT works with `npm run dev` (nollup).

**REPRODUCTION**: https://github.com/frederikhors/svelte-template-hot/tree/svelte-match-media-undefined.

I think there is everything to understand (there are few files).

If you need more, just ask, I'm here for you.

❤️

**Comment by frederikhors** [comment]
A small note:

I need to use `<script type='module' src='/bundle.js'></script>` for Nollup.

Instead of `<script type='module' src='/build/bundle.js'></script>` for Rollup.

(It would be nice to fix this too.)

**Comment by frederikhors** [comment]
I forgot the error:

`TypeError: Cannot read property 'desktop' of undefined`

**Comment by rixo** [comment]
`svelte-match-media` relies on a [live binding export](https://github.com/pearofducks/svelte-match-media/blob/b1cafe002b43a7208f9a0cad5059ca35b163d775/index.js#L17), and this is not supported by Nollup... Here's why.

To have the same script source in the HTML, you can set Nollup's `publicPath` option, for example in the command in package.json: `--public-path build` (full discussion [here](https://github.com/PepsRyuu/nollup/issues/84)).

Well, closing since there's nothing that can be done here... Either `svelte-match-media` releases a non-live-binding version for Nollup support, or Nollup should support live bindings (which they were reluctant to do until now because it's not a widely used feature and supporting it would impact Nollup's performance...).
