### ISSUE TITLE
Strange problem with svelte-calendar

### ISSUE THREAD

**Issue by antony** [rixo/rollup-plugin-svelte-hot#4]
So, HMR is working pretty well! There's one lib I'm having issues with, and that's svelte-calendar. For some reason the hot bundler can never seem to import it (says it can't be found)

https://github.com/antony/issue-hmr-calendar-issue

noticed this is to do with the lack of a `main` field. However, really it should be using the `svelte` field. Where does the fix for this lie?

**Comment by rixo** [comment]
Good catch!

And thanks for the repo, it made my life really easy :sunglasses: Maybe you should do such repros in some branches in a fork of the hot-template... I've already done things like this, you can end up with repository pollution pretty fast. Branches are less invasive... Just a tip ;)

I've migrated the issue to the Rollup plugin where the bug originated (don't bother trying to pick the right HMR project for reporting on your side, any is just fine -- but I prefer to have it here for reference and a proper issue number).

I've just release v0.5.0 of this plugin, that should fix this issue. (It also comes with better Svelte CSS support!) I've updated the hot template accordingly.

I'm not asking you to confirm it's fixed for you since I was able to do so myself with your repo, but feel free to reopen if needed. Thanks for the report :)
