### ISSUE TITLE
d3 function not found when using nollup

### ISSUE THREAD

**Issue by jacob-8** [rixo/rollup-plugin-svelte-hot#5]
Problem: When using d3.timeParse with Nollup, the function is undefined on the d3 object and my intended year temperature chart doesn't show.

Steps to reproduce:
1. `git clone https://github.com/jwrunner/athletic-line-chart.git`
2. `npm run dev:nollup`
3. Look in the console.log for "TypeError: d3.timeParse is not a function at drawLineChart" from App.svelte

Things work great when using `npm run dev:rollup` but I love how amazingly fast Nollup+HMR is!!! And I'm having trouble getting npm run dev:rollup to work on other devices over the network.

**Comment by jacob-8** [comment]
Just saw your fork to repro tip for Antony. I'll do that in the future.

**Comment by rixo** [comment]
Sorry for taking so long to get back at you... Thanks for the nice repro.

`d3` is apparently using ES live bindings exports for `timeParse` (you export a let variable, when you letter change the value, the change is seen by modules that have imported this export...).

And Nollup doesn't support live bindings...

So you need to either find a way to import this function that don't use live bindings... Or go and petition Nollup to support them. We've already discussed this briefly there, the author wasn't firmly opposed to add support behind an option. Maybe if this is required for `d3` support it would decide him...

I'm closing the issue since I don't think there's anything I can do from the projects I control to address that, unfortunately. Feel free to reopen if you think I've missed something.
